### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by mitsunorikawano** [mitsunorikawano/protospace-39297-2#1]
#URL
https://protospace-39297-2.onrender.com/

**Comment by motomuun** [comment]
@mitsunorikawano さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**プロトタイプ投稿機能**

- [x] **投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まること**
投稿に必要な情報が入力されていない場合、エラーページに遷移します。投稿ページに留まるように修正をお願いします。

- [x] **正しく投稿できた場合は、トップページへ遷移すること**
プロトタイプ詳細ページに遷移します。トップページに遷移するように修正をお願いします。



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mitsunorikawano** [comment]
【依頼】ProtoSpace挙動確認#1の修正分確認

**Comment by motomuun** [comment]
@mitsunorikawano さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
